### ISSUE TITLE
Unexplained ArgumentError

### ISSUE THREAD

**Issue by timwis** [conduitframework/conduit_amqp#13]
Hello, I'm having trouble diagnosing where this error is coming from and the stack trace isn't giving any clues :/ Any chance this looks familiar to you?

It's occuring when I publish jobs, and only for some of the jobs. I assume there's something wrong with the formatting of the job or something, and it's just swallowing the error somewhere along the way?

```
[error] ** (ArgumentError) argument error
[info] Processed message from data_digest.jobs in 759ms
[error] Task #PID<0.657.0> started from #PID<0.584.0> terminating
** (ArgumentError) argument error
    :erlang.byte_size(400)
    (data_digest) lib/data_digest_queue/subscribers/jobs_subscriber.ex:21: DataDigestQueue.JobsSubscriber.process/2
    (conduit) lib/conduit/plug/log_incoming.ex:26: Conduit.Plug.LogIncoming.call/3
    (conduit_amqp) lib/conduit_amqp/task.ex:16: ConduitAMQP.Task.run/6
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &ConduitAMQP.Task.run/6
    Args: [DataDigestQueue.Broker, %AMQP.Channel{conn: %AMQP.Connection{pid: #PID<0.595.0>}, pid: #PID<0.654.0>}, :jobs, "data_digest.jobs", <<31, 139, 8, 0, 0, 0, 0, 0, 0, 19, 109, 81, 193, 78, 195, 48, 12, 253, 149, 40, 210, 38, 144, 182, 102, 155, 64, 136, 106, 45, 59, 115, 224, 194, 145, 161, 201, 75, 188, 214, 83, 155, 148, 36, 101, ...>>, %{app_id: "data_digest", cluster_id: :undefined, consumer_tag: "amq.ctag-eHvPPCckn1r9NHb7Ax31jg", content_encoding: "gzip", content_type: "application/json", correlation_id: "93d21c60-0169-4aed-9164-ab09e1da06b8", delivery_tag: 1, exchange: "amq.topic", expiration: :undefined, headers: [{"created_at", :longstr, "2019-05-06T11:41:08.224457Z"}], message_id: :undefined, persistent: false, priority: :undefined, redelivered: true, reply_to: :undefined, routing_key: "data_digest.jobs", timestamp: :undefined, type: :undefined, user_id: :undefined}]
[error] ** (ArgumentError) argument error
[info] Processed message from data_digest.jobs in 829ms
13:11:58.000 [warning] lager_error_logger_h dropped 126 messages in the last second that exceeded the limit of 50 messages/sec
[error] Task #PID<0.658.0> started from #PID<0.584.0> terminating
** (ArgumentError) argument error
    :erlang.byte_size(400)
    (data_digest) lib/data_digest_queue/subscribers/jobs_subscriber.ex:21: DataDigestQueue.JobsSubscriber.process/2
    (conduit) lib/conduit/plug/log_incoming.ex:26: Conduit.Plug.LogIncoming.call/3
    (conduit_amqp) lib/conduit_amqp/task.ex:16: ConduitAMQP.Task.run/6
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &ConduitAMQP.Task.run/6
    Args: [DataDigestQueue.Broker, %AMQP.Channel{conn: %AMQP.Connection{pid: #PID<0.595.0>}, pid: #PID<0.654.0>}, :jobs, "data_digest.jobs", <<31, 139, 8, 0, 0, 0, 0, 0, 0, 19, 109, 81, 193, 78, 195, 48, 12, 253, 149, 40, 210, 38, 144, 182, 102, 155, 64, 136, 106, 45, 59, 115, 224, 194, 145, 161, 201, 75, 188, 214, 83, 155, 148, 36, 101, ...>>, %{app_id: "data_digest", cluster_id: :undefined, consumer_tag: "amq.ctag-eHvPPCckn1r9NHb7Ax31jg", content_encoding: "gzip", content_type: "application/json", correlation_id: "fc7f8bf9-57cf-464a-8464-ac2f00e6204e", delivery_tag: 2, exchange: "amq.topic", expiration: :undefined, headers: [{"created_at", :longstr, "2019-05-06T11:45:01.128109Z"}], message_id: :undefined, persistent: false, priority: :undefined, redelivered: true, reply_to: :undefined, routing_key: "data_digest.jobs", timestamp: :undefined, type: :undefined, user_id: :undefined}]
13:11:58.001 [error] ** Task <0.658.0> terminating
** Started from <0.584.0>
** When function  == fun Elixir.ConduitAMQP.Task:run/6
**      arguments == ['Elixir.DataDigestQueue.Broker',#{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.595.0>},pid => <0.654.0>},jobs,<<"data_digest.jobs">>,<<31,139,8,0,0,0,0,0,0,19,109,81,193,78,195,48,12,253,149,40,210,38,144,182,102,155,64,136,106,45,59,115,224,194,145,161,201,75,188,214,83,155,148,36,101,98,85,254,157,180,171,208,64,28,34,91,207,246,243,243,75,199,247,70,125,237,60,214,77,5,30,121,202,187,9,163,3,83,224,33,161,8,187,196,209,25,89,206,22,108,18,182,154,177,117,185,204,95,240,196,158,225,19,94,165,165,198,51,139,141,113,107,17,11,67,67,91,13,49,18,29,140,101,61,9,35,125,197,56,18,197,206,138,242,75,22,115,96,165,197,67,182,229,93,215,119,37,165,175,171,93,107,171,16,182,60,31,49,13,53,134,176,22,240,51,118,51,86,156,7,91,192,25,173,219,73,211,106,31,2,235,33,119,59,110,18,227,170,40,10,181,234,117,141,215,136,65,237,5,142,119,79,2,159,113,69,5,58,191,35,197,211,135,25,199,26,168,114,60,125,227,158,234,77,124,39,114,137,52,117,108,148,27,153,200,24,113,131,9,242,247,152,104,213,24,210,254,218,208,210,251,198,165,66,64,67,73,65,190,108,247,253,180,112,8,86,150,98,240,142,188,177,132,238,233,35,147,22,227,148,74,243,108,181,88,62,206,23,119,243,213,61,171,64,23,45,20,152,30,163,231,110,240,124,234,140,245,217,112,226,212,88,133,54,83,232,122,41,13,88,168,163,218,46,204,184,107,247,71,148,191,196,116,221,159,159,141,70,233,127,126,147,135,111,129,101,167,239,26,2,0,0>>,#{app_id => <<"data_digest">>,cluster_id => undefined,consumer_tag => <<"amq.ctag-eHvPPCckn1r9NHb7Ax31jg">>,content_encoding => <<"gzip">>,content_type => <<"application/json">>,correlation_id => <<"fc7f8bf9-57cf-464a-8464-ac2f00e6204e">>,delivery_tag => 2,exchange => <<"amq.topic">>,expiration => undefined,headers => [{<<"created_at">>,longstr,<<"2019-05-06T11:45:01.128109Z">>}],message_id => undefined,persistent => false,priority => undefined,redelivered => true,...}]
** Reason for termination ==
** {#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,byte_size,[400],[]},{'Elixir.DataDigestQueue.JobsSubscriber',process,2,[{file,"lib/data_digest_queue/subscribers/jobs_subscriber.ex"},{line,21}]},{'Elixir.Conduit.Plug.LogIncoming',call,3,[{file,"lib/conduit/plug/log_incoming.ex"},{line,26}]},{'Elixir.ConduitAMQP.Task',run,6,[{file,"lib/conduit_amqp/task.ex"},{line,16}]},{'Elixir.Task.Supervised',invoke_mfa,2,[{file,"lib/task/supervised.ex"},{line,90}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
13:11:58.001 [error] CRASH REPORT Process <0.658.0> with 0 neighbours crashed with reason: {#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,byte_size,[400],[]},{'Elixir.DataDigestQueue.JobsSubscriber',process,2,[{file,"lib/data_digest_queue/subscribers/jobs_subscriber.ex"},{line,21}]},{'Elixir.Conduit.Plug.LogIncoming',call,3,[{file,"lib/conduit/plug/log_incoming.ex"},{line,26}]},{'Elixir.ConduitAMQP.Task',run,6,[{file,"lib/conduit_amqp/task.ex"},{line,16}]},{'Elixir.Task.Supervised',invoke_mfa,2,[{file,"lib/task/supervis..."},...]},...]}
13:11:58.001 [error] Supervisor 'Elixir.DataDigestQueue.Broker.Adapter.Tasks' had child undefined started with {'Elixir.Task.Supervised',start_link,undefined} at <0.658.0> exit with reason {#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,byte_size,[400],[]},{'Elixir.DataDigestQueue.JobsSubscriber',process,2,[{file,"lib/data_digest_queue/subscribers/jobs_subscriber.ex"},{line,21}]},{'Elixir.Conduit.Plug.LogIncoming',call,3,[{file,"lib/conduit/plug/log_incoming.ex"},{line,26}]},{'Elixir.ConduitAMQP.Task',run,6,[{file,"lib/conduit_amqp/task.ex"},{line,16}]},{'Elixir.Task.Supervised',invoke_mfa,2,[{file,"lib/task/supervis..."},...]},...]} in context child_terminated
```

**Comment by blatyo** [comment]
The error appears to be coming from your code, which conduit has no control over.

Your error appears to say it's happening in this file `lib/data_digest_queue/subscribers/jobs_subscriber.ex` on line `21`. So, that's where I would look. If you need more help, try the [elixir forum](https://elixirforum.com). The people there are very responsive.

**Comment by timwis** [comment]
@blatyo I missed the `:21` in the stack trace so assumed conduit was simply swallowing the error details 🤦‍♂️ sorry about that, and thanks for pointing it out.
