### ISSUE TITLE
not compatible with conduit 0.12.1?

### ISSUE THREAD

**Issue by doughsay** [conduitframework/conduit_amqp#5]
I tried upgrading from conduit 0.11.0 to 0.12.1 and I get this error:

```
** (Mix) Could not start application api: API.Application.start(:normal, []) returned an error: shutdown: failed to start child: API.Broker
    ** (EXIT) shutdown: failed to start child: API.Broker.Adapter
        ** (EXIT) shutdown: failed to start child: API.Broker.Adapter.PubSub
            ** (EXIT) an exception was raised:
                ** (Protocol.UndefinedError) protocol String.Chars not implemented for {:<>, [context: API.BrokerHelper, import: Kernel, line: 6], ["noreaga.content/stream/activity", ".error"]}. This protocol is implemented for: Atom, BitString, Date, DateTime, Decimal, Ecto.Date, Ecto.DateTime, Ecto.Time, Float, Integer, List, Money, NaiveDateTime, Postgrex.Copy, Postgrex.Query, Postgrex.Stream, Time, URI, Version, Version.Requirement
                    (elixir) /home/ubuntu/bob/tmp/835867cc00c6933562caf44708cfd8f2/elixir/lib/elixir/lib/string/chars.ex:3: String.Chars.impl_for!/1
                    (elixir) /home/ubuntu/bob/tmp/835867cc00c6933562caf44708cfd8f2/elixir/lib/elixir/lib/string/chars.ex:22: String.Chars.to_string/1
                    (conduit_amqp) lib/conduit_amqp/topology.ex:38: anonymous fn/2 in ConduitAMQP.Topology.configure_queues/2
                    (elixir) lib/enum.ex:737: Enum."-each/2-lists^foreach/1-0-"/2
                    (elixir) lib/enum.ex:737: Enum.each/2
                    (conduit_amqp) lib/conduit_amqp/topology.ex:17: ConduitAMQP.Topology.configure/2
                    (conduit_amqp) lib/conduit_amqp/pub_sub.ex:24: ConduitAMQP.PubSub.init/1
                    (stdlib) supervisor.erl:294: :supervisor.init/1
```

**Comment by doughsay** [comment]
Sorry!  I didn't read it closely enough, it was a problem in a macro I'm using to generate the queue declarations.  Not sure why the upgrade caused it though...

**Comment by blatyo** [comment]
I changed the implementation of the internals for the DSL pretty substantially. It used to create nested modules under the broker. I changed it to only create the `receives` and `publish` functions. Based on the error, seems like maybe unintended  behavior where maybe your AST was getting put inline somewhere in the generated code. FYI, you can pass a function for the queue name. Here's an example: https://github.com/conduitframework/conduit/blob/master/test/conduit/broker_test.exs#L36
